### ISSUE TITLE
404 - Error Page.

### ISSUE THREAD

**Issue by edglz** [dannyribes/mystic-bcn-com#1]
He visto un error con el branding de la página, aún hay residuos de la web de los Esland.

### ¿Cómo reproducir el error?
[https://www.mystic-bcn.com/any](https://www.mystic-bcn.com/any)

![image](https://github.com/dannyribes/mystic-bcn-com/assets/122640934/1fa154ce-d84a-4854-890a-cbbe8a7d7a33)

**Comment by dannyribes** [comment]
Pues es verdad. Se me olvidó cambiar el logo. Muchas gracias. Ahora paso a corregirlo
